name: Build and upload custom engine to artifact

on:
  push:
      branches:
      - 'revenge'
      - 'add_workflow'
  workflow_dispatch:


jobs:    
  publish_artifact:
    name: Build and publish release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'npm'
      - run: |
          cd native
          git clone https://github.com/cocos/cocos-engine-external external
          cd external
          git checkout v3.8.4
      - name: Zip artifact
        run: |
          zip -r artifact.zip * -x "*/.git/*"  -x "*/node_modules/*"
      - name: Install GitHub CLI
        run: sudo apt-get install gh
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh release create v1.0.${{ github.run_number }}.${{ github.run_attempt }} artifact.zip  \
              --repo="${{ github.repository }}" \
              --title=""${{ github.repository }}" v1.0.${{ github.run_number }}.${{ github.run_attempt }}" \
              --generate-notes
      # - name: Upload Artifact
      #   run: |
      #     gh release upload v1.0.${{ github.run_number }}.${{ github.run_attempt }} artifact.zip
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}