name: Build and upload custom engine to artifact

on:
  push:
      branches:
      - 'revenge'
  workflow_dispatch:


jobs:    
  build_and_publish:
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'npm'
      - run: |
          npm install -g gulp
          cd native
          npm install
          gulp init
      # - name: Zip artifact
      #   run: |
      #     zip -r artifact.zip cocos-engine -x "*/.git/*"
      # - name: Upload environment variables
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: artifact
      #     path: artifact